version: "3.8"
name: shop-local

services:
  mysql:
    image: mysql:8.0
    container_name: db_shop_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data_local:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: shop_local_cont
    image: shop-app:local
    depends_on:
      - mysql
    volumes:
      - ./:/app
    ports:
      - "8080:8080"

volumes:
  db_data_local:
