version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: db_shop_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shop_dev_cont
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .env:/app/.env
    ports:
      - "8081:8080"
volumes:
  db_data:
